config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :blogs

  resources :users

  root 'blogs#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
 belongs_to :user

 validates(:text,
 			presence: true,
 			length: {maximum: 140})

 has_attached_file :avatar, styles:
   {medium: "300x300>", thumb: "100x100>"},
   default_url: ':style/missing.png',
   storage: :s3,
   s3_credentials: Proc.new{|a| a.instance.s3_credentials }
   		def s3_credentials
   			{bucket: "enzisbucket",
   			access_key_id: "AKIAJ66N3AXA4NNQ6VGQ",
   	        secret_access_key: "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"}
   	    end
   
   validates_attachment_content_type :avatar,
   content_type: /\Aimage\/.*\Z/

 def text_and_author
 	"#{text} by #{user.email}"
 end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_many :blogs

   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_action :authenticate_user!

	def index
		@blogs = Blog.all
	end

	def show
		find_blog
	end

	def new
		@blog = Blog.new
	end

	def create
		@blog = Blog.create(blog_params.merge(user: current_user))
		if @blog.valid?
			redirect_to(@blog)
		end
	end

	def edit
		find_blog
	end

	def update
		find_blog
		@blog.update(blog_params)
	end

	def destroy
		find_blog
		@blog.destroy
	end


private

	def find_blog 
		@blog = Blog.find(params[:id])
	end

	def blog_params
		params.require(:blog).permit(:text, :avatar)
		# .require isn't needed, but it is used to spit out an error
		#if no params are present.
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
		before_action :authenticate_user!

	def index
		@users = User.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
	def edit_blog_link(blog)
		link_to("Edit This Blog", edit_blog_url(blog))
	end
	
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/create.html.erb
<h1>There was an error!</h1>

<% @blog.errors.full_messages.each do |message| %>
	<p><%= message %></p>
<% end %>

<%= form_for(@blog) do |f| %>
	<p>
		<%= f.label(:text) %>
		<%= f.text_field(:text) %>
	</p>
	<%= image_tag @blog.avatar.url(:medium) %>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/blogs/destroy.html.erb
<h1>You destroyed your blog</h1>

app/views/blogs/edit.html.erb
<h1>Edit Blog</h1>

<%= form_for(@blog) do |f| %>
	<p>
		<%= f.label(:text) %>
		<%= f.text_field(:text) %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/blogs/index.html.erb
<h1>All Blogs</h1>

<p>There are <%= @blogs.count %> blogs.</p>

<% @blogs.each do |blog| %>
	<p>
		<%= link_to(blog.text_and_author, blog) %>
	</p>
		
	<p>
		<%= edit_blog_link(blog) %>
		<%= link_to('Delete', blog, method: :delete) %>
	</p>
<% end %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= form_for(@blog, html: {multipart: true}) do |f| %>
	<p>
		<%= f.label(:text) %>
		<%= f.text_field(:text) %>
	</p>
	<p>
		<%= f.label(:avatar) %>
		<%= f.file_field(:avatar) %>
	</p>
	<p>
		<%= f.submit %>
	</P>
<% end %>

app/views/blogs/show.html.erb
<h1>Blog Details</h1>
<p>This is blog #<%= @blog.id %></p>
<p><%= @blog.text %></p>
<% if @blog.avatar? %>
	<%= image_tag @blog.avatar.url %>
<% end %>
<p><%= edit_blog_link(@blog) %></p>

app/views/blogs/update.html.erb
<h1>Blog was edited</h1>

<p><%= @blog.text %></p>
<%= image_tag @blog.avatar.url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<ul>
		<li><%= link_to('All Blogs', blogs_url) %></li>
		<li><%= link_to('New Blog', new_blog_url) %></li>
		<li><%= link_to("All Users", users_url) %></li>
		<% if user_signed_in? %>
			<li>You are signed in as <%= current_user.email %></li>
			<li><%= link_to('Sign Out', destroy_user_session_url, method: :delete) %></li>
		<% else %>
			<li>You are not signed in</li>
			<li><%= link_to('Sign In', new_user_session_url) %></li>
		<% end %>
	</ul>
</header>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>List of all users</h1>

<p>There are <%= @users.count %> users.</p>

<% @users.each do |user| %>
	<p>
		<%= link_to(user.email, user) %>
	</p>
<% end %>